spring:

  application:
    name: service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 840831442772-27hm74kfo4dq6sb0jrtt8r6qatdr4s3b.apps.googleusercontent.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 18181
  servlet:
    context-path: /deepdivegallery
  forward-headers-strategy: framework

upload:
  application-home: true
  directory: uploads
  subdirectory-pattern: "^(.{4})(.{2})(.{2}).*$"
  whitelist:
    - image/bmp
    - image/gif
    - image/jpeg
    - image/pjpeg
    - image/png
    - image/tiff
  filename:
    format: "%1$s-%2$d.%3$s"
    randomizer-limit: 1000000
    timestamp:
      format: yyyyMMddHHmmssSSS
      time-zone: UTC
