spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 840831442772-27hm74kfo4dq6sb0jrtt8r6qatdr4s3b.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:deepdivegallery_db;create=true;collation=TERRITORY_BASED:PRIMARY

  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ddl.sql

server:
  port: 18181
  servlet:
    context-path: /deepdivegallery



